<?php

namespace AppBundle\Repository;

/**
 * TransitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransitRepository extends \Doctrine\ORM\EntityRepository
{
}
