version: '2'

services:

  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: ./docker/configs/php/
    env_file:
      - ./docker/config.env
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/configs/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ./docker/configs/php/php.ini:/usr/local/etc/php/conf.d/zz-php.ini
      - ./docker/configs/php/security.conf:/usr/local/etc/php-fpm.d/security.conf
      - ./logs/symfony:/var/www/symfony/app/logs
    mem_limit: 2000m
    memswap_limit: -1
    restart: unless-stopped
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./docker/config.env
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/configs/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx
    mem_limit: 2000m
    memswap_limit: -1
    restart: unless-stopped
    networks:
          - network
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./docker/config.env
    volumes:
      - ./data/db:/var/lib/mysql
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "1"
    mem_limit: 9g
    memswap_limit: -1
    restart: unless-stopped
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:mysql
    env_file:
      - ./docker/config.env
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - mysql
      - php

  elk:
    container_name: elk
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./symfony:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx
      - ./docker/configs/elk/logstash:/etc/logstash
      - ./docker/configs/elk/logstash/patterns:/opt/logstash/patterns

networks:
  network:
    driver: bridge